--- 
components: 
  schemas: 

    # This is the base definition of a building
    Building: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Building"
    # This is all of the defined building categories within
    # within the Smart Cities and Smart AgriFood domain
    BuildingCategory: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/openstreetmap.yaml#/Categories"

    # This is a base definition of an IoT Device
    Device: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/Device"
    # This is the full list of IoT Device Categories
    DeviceCategory: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/saref-terms.yaml#/Categories"
    # This is a full list of context attributes measurable by devices
    ControlledProperties: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/saref-terms.yaml#/ControlledProperties"

    # This is a defintion of a person.
    Person:
      allOf:
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/ngsi-ld.yaml#/Common"
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/Person"
    Gender:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/schema.org.yaml#/GenderType"
info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object